CREATE EXTENSION IF NOT EXISTS postgis;

DROP SCHEMA IF EXISTS dw CASCADE;
DROP SCHEMA IF EXISTS election CASCADE;
DROP SCHEMA IF EXISTS staging CASCADE;

CREATE SCHEMA staging;
CREATE SCHEMA election;
CREATE SCHEMA dw;
